CREATE TABLE IF NOT EXISTS ingredient (
`ID` INT NULL,
`name` VARCHAR(128) NULL
);

insert into DATABASE_NAME.ingredient (ID, name) values (1, 'Puree - Blackcurrant');
insert into DATABASE_NAME.ingredient (ID, name) values (2, 'Tuna - Salad Premix');
insert into DATABASE_NAME.ingredient (ID, name) values (3, 'Plasticforkblack');
insert into DATABASE_NAME.ingredient (ID, name) values (4, 'Sauce - Mint');
insert into DATABASE_NAME.ingredient (ID, name) values (5, 'Island Oasis - Ice Cream Mix');
insert into DATABASE_NAME.ingredient (ID, name) values (6, 'Wine - Lamancha Do Crianza');
insert into DATABASE_NAME.ingredient (ID, name) values (7, 'Coconut - Creamed, Pure');
insert into DATABASE_NAME.ingredient (ID, name) values (8, 'Basil - Pesto Sauce');
insert into DATABASE_NAME.ingredient (ID, name) values (9, 'Bread - Multigrain Oval');
insert into DATABASE_NAME.ingredient (ID, name) values (10, 'Urban Zen Drinks');
insert into DATABASE_NAME.ingredient (ID, name) values (11, 'Yogurt - Cherry, 175 Gr');
insert into DATABASE_NAME.ingredient (ID, name) values (12, 'Bread - Rolls, Rye');
insert into DATABASE_NAME.ingredient (ID, name) values (13, 'Bar Nature Valley');
insert into DATABASE_NAME.ingredient (ID, name) values (14, 'Gatorade - Orange');
insert into DATABASE_NAME.ingredient (ID, name) values (15, 'Dried Peach');
insert into DATABASE_NAME.ingredient (ID, name) values (16, 'Sugar - Palm');
insert into DATABASE_NAME.ingredient (ID, name) values (17, 'Pastry - Baked Scones - Mini');
insert into DATABASE_NAME.ingredient (ID, name) values (18, 'Container - Hngd Cll Blk 7x7x3');
insert into DATABASE_NAME.ingredient (ID, name) values (19, 'Beef Cheek Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (20, 'Cabbage - Savoy');
insert into DATABASE_NAME.ingredient (ID, name) values (21, 'Muffin Puck Ww Carrot');
insert into DATABASE_NAME.ingredient (ID, name) values (22, 'Syrup - Monin - Passion Fruit');
insert into DATABASE_NAME.ingredient (ID, name) values (23, 'Pasta - Fettuccine, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (24, 'Puree - Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (25, 'Mustard - Seed');
insert into DATABASE_NAME.ingredient (ID, name) values (26, 'Soup - Campbells, Creamy');
insert into DATABASE_NAME.ingredient (ID, name) values (27, 'Beef - Tenderlion, Center Cut');
insert into DATABASE_NAME.ingredient (ID, name) values (28, 'Foam Dinner Plate');
insert into DATABASE_NAME.ingredient (ID, name) values (29, 'Bread - Raisin Walnut Oval');
insert into DATABASE_NAME.ingredient (ID, name) values (30, 'Walkers Special Old Whiskey');
insert into DATABASE_NAME.ingredient (ID, name) values (31, 'Wine - White, French Cross');
insert into DATABASE_NAME.ingredient (ID, name) values (32, 'Table Cloth 81x81 White');
insert into DATABASE_NAME.ingredient (ID, name) values (33, 'Tart Shells - Savory, 3');
insert into DATABASE_NAME.ingredient (ID, name) values (34, 'Chicken - Bones');
insert into DATABASE_NAME.ingredient (ID, name) values (35, 'Cleaner - Pine Sol');
insert into DATABASE_NAME.ingredient (ID, name) values (36, 'Muffin Mix - Blueberry');
insert into DATABASE_NAME.ingredient (ID, name) values (37, 'Figs');
insert into DATABASE_NAME.ingredient (ID, name) values (38, 'Soup - Campbells, Chix Gumbo');
insert into DATABASE_NAME.ingredient (ID, name) values (39, 'Tea - Decaf Lipton');
insert into DATABASE_NAME.ingredient (ID, name) values (40, 'Pepper - Chilli Seeds Mild');
insert into DATABASE_NAME.ingredient (ID, name) values (41, 'Sugar Thermometer');
insert into DATABASE_NAME.ingredient (ID, name) values (42, 'Juice - Lemon');
insert into DATABASE_NAME.ingredient (ID, name) values (43, 'Wine - Casillero Del Diablo');
insert into DATABASE_NAME.ingredient (ID, name) values (44, 'Cafe Royale');
insert into DATABASE_NAME.ingredient (ID, name) values (45, 'Onion Powder');
insert into DATABASE_NAME.ingredient (ID, name) values (46, 'Pie Pecan');
insert into DATABASE_NAME.ingredient (ID, name) values (47, 'Basil - Dry, Rubbed');
insert into DATABASE_NAME.ingredient (ID, name) values (48, 'Wine - George Duboeuf Rose');
insert into DATABASE_NAME.ingredient (ID, name) values (49, 'Flower - Commercial Bronze');
insert into DATABASE_NAME.ingredient (ID, name) values (50, 'Shrimp - Tiger 21/25');
insert into DATABASE_NAME.ingredient (ID, name) values (51, 'Daikon Radish');
insert into DATABASE_NAME.ingredient (ID, name) values (52, 'Ecolab - Orange Frc, Cleaner');
insert into DATABASE_NAME.ingredient (ID, name) values (53, 'Lobster - Tail, 3 - 4 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (54, 'Carrots - Mini Red Organic');
insert into DATABASE_NAME.ingredient (ID, name) values (55, 'Juice - Orange');
insert into DATABASE_NAME.ingredient (ID, name) values (56, 'Spaghetti Squash');
insert into DATABASE_NAME.ingredient (ID, name) values (57, 'Lentils - Red, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (58, 'Flower - Potmums');
insert into DATABASE_NAME.ingredient (ID, name) values (59, 'Rolled Oats');
insert into DATABASE_NAME.ingredient (ID, name) values (60, 'Mangostein');
insert into DATABASE_NAME.ingredient (ID, name) values (61, 'Sesame Seed Black');
insert into DATABASE_NAME.ingredient (ID, name) values (62, 'Cookie Choc');
insert into DATABASE_NAME.ingredient (ID, name) values (63, 'Pastry - Key Limepoppy Seed Tea');
insert into DATABASE_NAME.ingredient (ID, name) values (64, 'Foam Espresso Cup Plain White');
insert into DATABASE_NAME.ingredient (ID, name) values (65, 'Garlic - Elephant');
insert into DATABASE_NAME.ingredient (ID, name) values (66, 'Coffee Decaf Colombian');
insert into DATABASE_NAME.ingredient (ID, name) values (67, 'Milk - Chocolate 500ml');
insert into DATABASE_NAME.ingredient (ID, name) values (68, 'Glass - Juice Clear 5oz 55005');
insert into DATABASE_NAME.ingredient (ID, name) values (69, 'Bols Melon Liqueur');
insert into DATABASE_NAME.ingredient (ID, name) values (70, 'Cheese - Blue');
insert into DATABASE_NAME.ingredient (ID, name) values (71, 'Cookie Dough - Peanut Butter');
insert into DATABASE_NAME.ingredient (ID, name) values (72, 'Wine - Chianti Classico Riserva');
insert into DATABASE_NAME.ingredient (ID, name) values (73, 'Soup - Campbells, Spinach Crm');
insert into DATABASE_NAME.ingredient (ID, name) values (74, 'Wine - Magnotta - Cab Franc');
insert into DATABASE_NAME.ingredient (ID, name) values (75, 'Sauce - Thousand Island');
insert into DATABASE_NAME.ingredient (ID, name) values (76, 'Cornish Hen');
insert into DATABASE_NAME.ingredient (ID, name) values (77, 'Crawfish');
insert into DATABASE_NAME.ingredient (ID, name) values (78, 'Apron');
insert into DATABASE_NAME.ingredient (ID, name) values (79, 'Puree - Kiwi');
insert into DATABASE_NAME.ingredient (ID, name) values (80, 'Chocolate - Milk');
insert into DATABASE_NAME.ingredient (ID, name) values (81, 'Beef - Bresaola');
insert into DATABASE_NAME.ingredient (ID, name) values (82, 'Wine - Prosecco Valdobiaddene');
insert into DATABASE_NAME.ingredient (ID, name) values (83, 'Table Cloth 62x120 Colour');
insert into DATABASE_NAME.ingredient (ID, name) values (84, 'C - Plus, Orange');
insert into DATABASE_NAME.ingredient (ID, name) values (85, 'Beef - Top Butt');
insert into DATABASE_NAME.ingredient (ID, name) values (86, 'Vinegar - Red Wine');
insert into DATABASE_NAME.ingredient (ID, name) values (87, 'Pepper - Scotch Bonnet');
insert into DATABASE_NAME.ingredient (ID, name) values (88, 'Cleaner - Pine Sol');
insert into DATABASE_NAME.ingredient (ID, name) values (89, 'Galliano');
insert into DATABASE_NAME.ingredient (ID, name) values (90, 'Stock - Veal, White');
insert into DATABASE_NAME.ingredient (ID, name) values (91, 'Table Cloth 54x54 Colour');
insert into DATABASE_NAME.ingredient (ID, name) values (92, 'Pasta - Gnocchi, Potato');
insert into DATABASE_NAME.ingredient (ID, name) values (93, 'Rosemary - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (94, 'Wine - Pinot Noir Mondavi Coastal');
insert into DATABASE_NAME.ingredient (ID, name) values (95, 'Bread - White Mini Epi');
insert into DATABASE_NAME.ingredient (ID, name) values (96, 'Lobster - Live');
insert into DATABASE_NAME.ingredient (ID, name) values (97, 'Seedlings - Mix, Organic');
insert into DATABASE_NAME.ingredient (ID, name) values (98, 'Wine - Prosecco Valdobienne');
insert into DATABASE_NAME.ingredient (ID, name) values (99, 'Rolled Oats');
insert into DATABASE_NAME.ingredient (ID, name) values (100, 'Red Currants');
insert into DATABASE_NAME.ingredient (ID, name) values (101, 'Chicken Breast Halal');
insert into DATABASE_NAME.ingredient (ID, name) values (102, 'Yeast Dry - Fleischman');
insert into DATABASE_NAME.ingredient (ID, name) values (103, 'Muffin Mix - Corn Harvest');
insert into DATABASE_NAME.ingredient (ID, name) values (104, 'Pasta - Orzo, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (105, 'Shrimp - 16 - 20 Cooked, Peeled');
insert into DATABASE_NAME.ingredient (ID, name) values (106, 'Calypso - Lemonade');
insert into DATABASE_NAME.ingredient (ID, name) values (107, 'Tray - 16in Rnd Blk');
insert into DATABASE_NAME.ingredient (ID, name) values (108, 'Chicken - Wieners');
insert into DATABASE_NAME.ingredient (ID, name) values (109, 'Garam Masala Powder');
insert into DATABASE_NAME.ingredient (ID, name) values (110, 'Lady Fingers');
insert into DATABASE_NAME.ingredient (ID, name) values (111, 'Juice - Pineapple, 48 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (112, 'Compound - Orange');
insert into DATABASE_NAME.ingredient (ID, name) values (113, 'Liquid Aminios Acid - Braggs');
insert into DATABASE_NAME.ingredient (ID, name) values (114, 'Lettuce - Romaine, Heart');
insert into DATABASE_NAME.ingredient (ID, name) values (115, 'Vinegar - Cider');
insert into DATABASE_NAME.ingredient (ID, name) values (116, 'Spice - Pepper Portions');
insert into DATABASE_NAME.ingredient (ID, name) values (117, 'Coffee - Hazelnut Cream');
insert into DATABASE_NAME.ingredient (ID, name) values (118, 'Pepper - Scotch Bonnet');
insert into DATABASE_NAME.ingredient (ID, name) values (119, 'Ice Cream - Strawberry');
insert into DATABASE_NAME.ingredient (ID, name) values (120, 'Bread - Malt');
insert into DATABASE_NAME.ingredient (ID, name) values (121, 'Sausage - Chorizo');
insert into DATABASE_NAME.ingredient (ID, name) values (122, 'Brownies - Two Bite, Chocolate');
insert into DATABASE_NAME.ingredient (ID, name) values (123, 'Turkey Leg With Drum And Thigh');
insert into DATABASE_NAME.ingredient (ID, name) values (124, 'Anchovy Fillets');
insert into DATABASE_NAME.ingredient (ID, name) values (125, 'Wanton Wrap');
insert into DATABASE_NAME.ingredient (ID, name) values (126, 'Gelatine Leaves - Bulk');
insert into DATABASE_NAME.ingredient (ID, name) values (127, 'Yoplait - Strawbrasp Peac');
insert into DATABASE_NAME.ingredient (ID, name) values (128, 'Shiro Miso');
insert into DATABASE_NAME.ingredient (ID, name) values (129, 'Chicken - Wieners');
insert into DATABASE_NAME.ingredient (ID, name) values (130, 'Sauce - Mint');
insert into DATABASE_NAME.ingredient (ID, name) values (131, 'Pear - Prickly');
insert into DATABASE_NAME.ingredient (ID, name) values (132, 'Dikon');
insert into DATABASE_NAME.ingredient (ID, name) values (133, 'Pate - Peppercorn');
insert into DATABASE_NAME.ingredient (ID, name) values (134, 'Pepper - Roasted Red');
insert into DATABASE_NAME.ingredient (ID, name) values (135, 'Island Oasis - Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (136, 'Wine - Zonnebloem Pinotage');
insert into DATABASE_NAME.ingredient (ID, name) values (137, 'Soup - French Onion, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (138, 'Oregano - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (139, 'Vinegar - Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (140, 'Food Colouring - Blue');
insert into DATABASE_NAME.ingredient (ID, name) values (141, 'Beer - Sleemans Honey Brown');
insert into DATABASE_NAME.ingredient (ID, name) values (142, 'Chevere Logs');
insert into DATABASE_NAME.ingredient (ID, name) values (143, 'Wine - Port Late Bottled Vintage');
insert into DATABASE_NAME.ingredient (ID, name) values (144, 'Goulash Seasoning');
insert into DATABASE_NAME.ingredient (ID, name) values (145, 'Mint - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (146, 'Salmon - Atlantic, Skin On');
insert into DATABASE_NAME.ingredient (ID, name) values (147, 'Hipnotiq Liquor');
insert into DATABASE_NAME.ingredient (ID, name) values (148, 'Wheat - Soft Kernal Of Wheat');
insert into DATABASE_NAME.ingredient (ID, name) values (149, 'Water - Spring Water, 355 Ml');
insert into DATABASE_NAME.ingredient (ID, name) values (150, 'Mushroom - Porcini, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (151, 'Bar Bran Honey Nut');
insert into DATABASE_NAME.ingredient (ID, name) values (152, 'Butter - Salted, Micro');
insert into DATABASE_NAME.ingredient (ID, name) values (153, 'Breadfruit');
insert into DATABASE_NAME.ingredient (ID, name) values (154, 'Cheese - Cheddar With Claret');
insert into DATABASE_NAME.ingredient (ID, name) values (155, 'Pasta - Detalini, White, Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (156, 'Onions - Red');
insert into DATABASE_NAME.ingredient (ID, name) values (157, 'Bread Base - Gold Formel');
insert into DATABASE_NAME.ingredient (ID, name) values (158, 'Gloves - Goldtouch Disposable');
insert into DATABASE_NAME.ingredient (ID, name) values (159, 'Tamarillo');
insert into DATABASE_NAME.ingredient (ID, name) values (160, 'Apple - Delicious, Red');
insert into DATABASE_NAME.ingredient (ID, name) values (161, 'Onion Powder');
insert into DATABASE_NAME.ingredient (ID, name) values (162, 'Bread - Pullman, Sliced');
insert into DATABASE_NAME.ingredient (ID, name) values (163, 'Pop Shoppe Cream Soda');
insert into DATABASE_NAME.ingredient (ID, name) values (164, 'Mousse - Banana Chocolate');
insert into DATABASE_NAME.ingredient (ID, name) values (165, 'Star Fruit');
insert into DATABASE_NAME.ingredient (ID, name) values (166, 'Milk - Chocolate 500ml');
insert into DATABASE_NAME.ingredient (ID, name) values (167, 'Kiwi Gold Zespri');
insert into DATABASE_NAME.ingredient (ID, name) values (168, 'Dried Cranberries');
insert into DATABASE_NAME.ingredient (ID, name) values (169, 'Pork - Butt, Boneless');
insert into DATABASE_NAME.ingredient (ID, name) values (170, 'Chervil - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (171, 'Mushroom - Lg - Cello');
insert into DATABASE_NAME.ingredient (ID, name) values (172, 'Cattail Hearts');
insert into DATABASE_NAME.ingredient (ID, name) values (173, 'Flour - Pastry');
insert into DATABASE_NAME.ingredient (ID, name) values (174, 'Cognac - Courvaisier');
insert into DATABASE_NAME.ingredient (ID, name) values (175, 'Juice - Pineapple, 48 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (176, 'Hot Chocolate - Individual');
insert into DATABASE_NAME.ingredient (ID, name) values (177, 'Vanilla Beans');
insert into DATABASE_NAME.ingredient (ID, name) values (178, 'Tea - Jasmin Green');
insert into DATABASE_NAME.ingredient (ID, name) values (179, 'Hog / Sausage Casing - Pork');
insert into DATABASE_NAME.ingredient (ID, name) values (180, 'Crab - Imitation Flakes');
insert into DATABASE_NAME.ingredient (ID, name) values (181, 'Chips Potato Salt Vinegar 43g');
insert into DATABASE_NAME.ingredient (ID, name) values (182, 'Tomato - Tricolor Cherry');
insert into DATABASE_NAME.ingredient (ID, name) values (183, 'Sardines');
insert into DATABASE_NAME.ingredient (ID, name) values (184, 'Beans - Kidney, Red Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (185, 'Table Cloth 72x144 White');
insert into DATABASE_NAME.ingredient (ID, name) values (186, 'Ecolab - Orange Frc, Cleaner');
insert into DATABASE_NAME.ingredient (ID, name) values (187, 'Salmon Steak - Cohoe 8 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (188, 'Pie Shells 10');
insert into DATABASE_NAME.ingredient (ID, name) values (189, 'Lid - 0090 Clear');
insert into DATABASE_NAME.ingredient (ID, name) values (190, 'Wine - Two Oceans Sauvignon');
insert into DATABASE_NAME.ingredient (ID, name) values (191, 'Thermometer Digital');
insert into DATABASE_NAME.ingredient (ID, name) values (192, 'Burger Veggie');
insert into DATABASE_NAME.ingredient (ID, name) values (193, 'Chicken - White Meat With Tender');
insert into DATABASE_NAME.ingredient (ID, name) values (194, 'Peppercorns - Pink');
insert into DATABASE_NAME.ingredient (ID, name) values (195, 'Carrots - Jumbo');
insert into DATABASE_NAME.ingredient (ID, name) values (196, 'Iced Tea Concentrate');
insert into DATABASE_NAME.ingredient (ID, name) values (197, 'Pail For Lid 1537');
insert into DATABASE_NAME.ingredient (ID, name) values (198, 'Cheese - Cheddarsliced');
insert into DATABASE_NAME.ingredient (ID, name) values (199, 'Oyster - In Shell');
insert into DATABASE_NAME.ingredient (ID, name) values (200, 'Veal - Liver');
insert into DATABASE_NAME.ingredient (ID, name) values (201, 'Beans - Black Bean, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (202, 'Muffin - Mix - Bran And Maple 15l');
insert into DATABASE_NAME.ingredient (ID, name) values (203, 'Mushroom Morel Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (204, 'Wine - Toasted Head');
insert into DATABASE_NAME.ingredient (ID, name) values (205, 'Chickensplit Half');
insert into DATABASE_NAME.ingredient (ID, name) values (206, 'Veal - Chops, Split, Frenched');
insert into DATABASE_NAME.ingredient (ID, name) values (207, 'Sugar - Palm');
insert into DATABASE_NAME.ingredient (ID, name) values (208, 'Wine - Merlot Vina Carmen');
insert into DATABASE_NAME.ingredient (ID, name) values (209, 'Salmon - Smoked, Sliced');
insert into DATABASE_NAME.ingredient (ID, name) values (210, 'Dried Cranberries');
insert into DATABASE_NAME.ingredient (ID, name) values (211, 'Sprouts - Onion');
insert into DATABASE_NAME.ingredient (ID, name) values (212, 'Hersey Shakes');
insert into DATABASE_NAME.ingredient (ID, name) values (213, 'Veal - Osso Bucco');
insert into DATABASE_NAME.ingredient (ID, name) values (214, 'Bread - Pita, Mini');
insert into DATABASE_NAME.ingredient (ID, name) values (215, 'The Pop Shoppe - Root Beer');
insert into DATABASE_NAME.ingredient (ID, name) values (216, 'Cornstarch');
insert into DATABASE_NAME.ingredient (ID, name) values (217, 'Napkin - Dinner, White');
insert into DATABASE_NAME.ingredient (ID, name) values (218, 'Vanilla Beans');
insert into DATABASE_NAME.ingredient (ID, name) values (219, 'Squid U5 - Thailand');
insert into DATABASE_NAME.ingredient (ID, name) values (220, 'Tomatillo');
insert into DATABASE_NAME.ingredient (ID, name) values (221, 'Barramundi');
insert into DATABASE_NAME.ingredient (ID, name) values (222, 'Cake - Miini Cheesecake Cherry');
insert into DATABASE_NAME.ingredient (ID, name) values (223, 'Puree - Mocha');
insert into DATABASE_NAME.ingredient (ID, name) values (224, 'Spice - Peppercorn Melange');
insert into DATABASE_NAME.ingredient (ID, name) values (225, 'Nut - Almond, Blanched, Ground');
insert into DATABASE_NAME.ingredient (ID, name) values (226, 'Mint - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (227, 'Wine - Red, Gamay Noir');
insert into DATABASE_NAME.ingredient (ID, name) values (228, 'Lid Coffeecup 12oz D9542b');
insert into DATABASE_NAME.ingredient (ID, name) values (229, 'Broom - Push');
insert into DATABASE_NAME.ingredient (ID, name) values (230, 'Beans - Wax');
insert into DATABASE_NAME.ingredient (ID, name) values (231, 'Pork Ham Prager');
insert into DATABASE_NAME.ingredient (ID, name) values (232, 'Breadfruit');
insert into DATABASE_NAME.ingredient (ID, name) values (233, 'Wine - Sauvignon Blanc Oyster');
insert into DATABASE_NAME.ingredient (ID, name) values (234, 'Allspice - Jamaican');
insert into DATABASE_NAME.ingredient (ID, name) values (235, 'Jagermeister');
insert into DATABASE_NAME.ingredient (ID, name) values (236, 'Cheese - Shred Cheddar / Mozza');
insert into DATABASE_NAME.ingredient (ID, name) values (237, 'Lid - 0090 Clear');
insert into DATABASE_NAME.ingredient (ID, name) values (238, 'Cabbage - Red');
insert into DATABASE_NAME.ingredient (ID, name) values (239, 'Lemon Grass');
insert into DATABASE_NAME.ingredient (ID, name) values (240, 'Tomatoes - Cherry');
insert into DATABASE_NAME.ingredient (ID, name) values (241, 'Oven Mitt - 13 Inch');
insert into DATABASE_NAME.ingredient (ID, name) values (242, 'Bread Bowl Plain');
insert into DATABASE_NAME.ingredient (ID, name) values (243, 'Zucchini - Green');
insert into DATABASE_NAME.ingredient (ID, name) values (244, 'Wine - Red, Gallo, Merlot');
insert into DATABASE_NAME.ingredient (ID, name) values (245, 'Beans - Black Bean, Canned');
insert into DATABASE_NAME.ingredient (ID, name) values (246, 'Wine - White, Colubia Cresh');
insert into DATABASE_NAME.ingredient (ID, name) values (247, 'Blouse / Shirt / Sweater');
insert into DATABASE_NAME.ingredient (ID, name) values (248, 'Bread - Pumpernickel');
insert into DATABASE_NAME.ingredient (ID, name) values (249, 'Wine - Sogrape Mateus Rose');
insert into DATABASE_NAME.ingredient (ID, name) values (250, 'Lemonade - Natural, 591 Ml');
insert into DATABASE_NAME.ingredient (ID, name) values (251, 'Oats Large Flake');
insert into DATABASE_NAME.ingredient (ID, name) values (252, 'Cheese - Swiss Sliced');
insert into DATABASE_NAME.ingredient (ID, name) values (253, 'Cleaner - Pine Sol');
insert into DATABASE_NAME.ingredient (ID, name) values (254, 'The Pop Shoppe Pinapple');
insert into DATABASE_NAME.ingredient (ID, name) values (255, 'Vanilla Beans');
insert into DATABASE_NAME.ingredient (ID, name) values (256, 'Wine - Placido Pinot Grigo');
insert into DATABASE_NAME.ingredient (ID, name) values (257, 'Cognac - Courvaisier');
insert into DATABASE_NAME.ingredient (ID, name) values (258, 'Fudge - Chocolate Fudge');
insert into DATABASE_NAME.ingredient (ID, name) values (259, 'Pepperoni Slices');
insert into DATABASE_NAME.ingredient (ID, name) values (260, 'Dc Hikiage Hira Huba');
insert into DATABASE_NAME.ingredient (ID, name) values (261, 'Pastry - Lemon Danish - Mini');
insert into DATABASE_NAME.ingredient (ID, name) values (262, 'Wine - White, Schroder And Schyl');
insert into DATABASE_NAME.ingredient (ID, name) values (263, 'Pastry - Banana Tea Loaf');
insert into DATABASE_NAME.ingredient (ID, name) values (264, 'Cake - Sheet Strawberry');
insert into DATABASE_NAME.ingredient (ID, name) values (265, 'Fiddlehead - Frozen');
insert into DATABASE_NAME.ingredient (ID, name) values (266, 'Tumeric');
insert into DATABASE_NAME.ingredient (ID, name) values (267, 'Beer - Moosehead');
insert into DATABASE_NAME.ingredient (ID, name) values (268, 'Bread - Multigrain, Loaf');
insert into DATABASE_NAME.ingredient (ID, name) values (269, 'Wine - White, French Cross');
insert into DATABASE_NAME.ingredient (ID, name) values (270, 'Basil - Seedlings Cookstown');
insert into DATABASE_NAME.ingredient (ID, name) values (271, 'Beef - Outside, Round');
insert into DATABASE_NAME.ingredient (ID, name) values (272, 'Transfer Sheets');
insert into DATABASE_NAME.ingredient (ID, name) values (273, 'Pail With Metal Handle 16l White');
insert into DATABASE_NAME.ingredient (ID, name) values (274, 'Tendrils - Baby Pea, Organic');
insert into DATABASE_NAME.ingredient (ID, name) values (275, 'Rum - Light, Captain Morgan');
insert into DATABASE_NAME.ingredient (ID, name) values (276, 'Crackers - Melba Toast');
insert into DATABASE_NAME.ingredient (ID, name) values (277, 'Tea - Apple Green Tea');
insert into DATABASE_NAME.ingredient (ID, name) values (278, 'Wine - Vouvray Cuvee Domaine');
insert into DATABASE_NAME.ingredient (ID, name) values (279, 'Marsala - Sperone, Fine, D.o.c.');
insert into DATABASE_NAME.ingredient (ID, name) values (280, 'Muffins - Assorted');
insert into DATABASE_NAME.ingredient (ID, name) values (281, 'Quail - Jumbo');
insert into DATABASE_NAME.ingredient (ID, name) values (282, 'Lamb - Loin Chops');
insert into DATABASE_NAME.ingredient (ID, name) values (283, 'Oil - Safflower');
insert into DATABASE_NAME.ingredient (ID, name) values (284, 'Table Cloth - 53x69 Colour');
insert into DATABASE_NAME.ingredient (ID, name) values (285, 'Lid - 16 Oz And 32 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (286, 'Nectarines');
insert into DATABASE_NAME.ingredient (ID, name) values (287, 'Sauce - Salsa');
insert into DATABASE_NAME.ingredient (ID, name) values (288, 'Soup - Campbells Pasta Fagioli');
insert into DATABASE_NAME.ingredient (ID, name) values (289, 'Beer - Sleeman Fine Porter');
insert into DATABASE_NAME.ingredient (ID, name) values (290, 'Chick Peas - Dried');
insert into DATABASE_NAME.ingredient (ID, name) values (291, 'Foil Cont Round');
insert into DATABASE_NAME.ingredient (ID, name) values (292, 'Bread Base - Goodhearth');
insert into DATABASE_NAME.ingredient (ID, name) values (293, 'Samosa - Veg');
insert into DATABASE_NAME.ingredient (ID, name) values (294, 'Gelatine Leaves - Envelopes');
insert into DATABASE_NAME.ingredient (ID, name) values (295, 'Tahini Paste');
insert into DATABASE_NAME.ingredient (ID, name) values (296, 'Flower - Dish Garden');
insert into DATABASE_NAME.ingredient (ID, name) values (297, 'Wine - Beringer Founders Estate');
insert into DATABASE_NAME.ingredient (ID, name) values (298, 'Wine - Gato Negro Cabernet');
insert into DATABASE_NAME.ingredient (ID, name) values (299, 'Wine - Penfolds Koonuga Hill');
insert into DATABASE_NAME.ingredient (ID, name) values (300, 'Shrimp - 16 - 20 Cooked, Peeled');
insert into DATABASE_NAME.ingredient (ID, name) values (301, 'Vinegar - Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (302, 'Tomatoes - Hot House');
insert into DATABASE_NAME.ingredient (ID, name) values (303, 'Sauce Tomato Pouch');
insert into DATABASE_NAME.ingredient (ID, name) values (304, 'Lid - 3oz Med Rec');
insert into DATABASE_NAME.ingredient (ID, name) values (305, 'Soup - Chicken And Wild Rice');
insert into DATABASE_NAME.ingredient (ID, name) values (306, 'Soho Lychee Liqueur');
insert into DATABASE_NAME.ingredient (ID, name) values (307, 'Cheese - Ermite Bleu');
insert into DATABASE_NAME.ingredient (ID, name) values (308, 'Plastic Wrap');
insert into DATABASE_NAME.ingredient (ID, name) values (309, 'Gelatine Powder');
insert into DATABASE_NAME.ingredient (ID, name) values (310, 'Doilies - 10, Paper');
insert into DATABASE_NAME.ingredient (ID, name) values (311, 'Vermouth - White, Cinzano');
insert into DATABASE_NAME.ingredient (ID, name) values (312, 'Muffin Chocolate Individual Wrap');
insert into DATABASE_NAME.ingredient (ID, name) values (313, 'Chocolate - Feathers');
insert into DATABASE_NAME.ingredient (ID, name) values (314, 'Magnotta - Bel Paese White');
insert into DATABASE_NAME.ingredient (ID, name) values (315, 'Snapple Raspberry Tea');
insert into DATABASE_NAME.ingredient (ID, name) values (316, 'Poppy Seed');
insert into DATABASE_NAME.ingredient (ID, name) values (317, 'Ecolab - Ster Bac');
insert into DATABASE_NAME.ingredient (ID, name) values (318, 'Cheese - Cheddar With Claret');
insert into DATABASE_NAME.ingredient (ID, name) values (319, 'Bagel - 12 Grain Preslice');
insert into DATABASE_NAME.ingredient (ID, name) values (320, 'Lamb - Loin, Trimmed, Boneless');
insert into DATABASE_NAME.ingredient (ID, name) values (321, 'Pork - Bacon Cooked Slcd');
insert into DATABASE_NAME.ingredient (ID, name) values (322, 'Table Cloth 144x90 White');
insert into DATABASE_NAME.ingredient (ID, name) values (323, 'Sauce - Chili');
insert into DATABASE_NAME.ingredient (ID, name) values (324, 'Vermouth - White, Cinzano');
insert into DATABASE_NAME.ingredient (ID, name) values (325, 'Island Oasis - Magarita Mix');
insert into DATABASE_NAME.ingredient (ID, name) values (326, 'Pastry - French Mini Assorted');
insert into DATABASE_NAME.ingredient (ID, name) values (327, 'Pepper - Jalapeno');
insert into DATABASE_NAME.ingredient (ID, name) values (328, 'Lettuce - Romaine');
insert into DATABASE_NAME.ingredient (ID, name) values (329, 'Crackers Cheez It');
insert into DATABASE_NAME.ingredient (ID, name) values (330, 'Oil - Peanut');
insert into DATABASE_NAME.ingredient (ID, name) values (331, 'Schnappes Peppermint - Walker');
insert into DATABASE_NAME.ingredient (ID, name) values (332, 'Syrup - Monin, Amaretta');
insert into DATABASE_NAME.ingredient (ID, name) values (333, 'Table Cloth 62x120 Colour');
insert into DATABASE_NAME.ingredient (ID, name) values (334, 'Wine - Black Tower Qr');
insert into DATABASE_NAME.ingredient (ID, name) values (335, 'Vermouth - Sweet, Cinzano');
insert into DATABASE_NAME.ingredient (ID, name) values (336, 'Table Cloth 53x69 White');
insert into DATABASE_NAME.ingredient (ID, name) values (337, 'Oneshot Automatic Soap System');
insert into DATABASE_NAME.ingredient (ID, name) values (338, 'Flower - Dish Garden');
insert into DATABASE_NAME.ingredient (ID, name) values (339, 'Yogurt - Raspberry, 175 Gr');
insert into DATABASE_NAME.ingredient (ID, name) values (340, 'Bar - Sweet And Salty Chocolate');
insert into DATABASE_NAME.ingredient (ID, name) values (341, 'Pastry - Lemon Danish - Mini');
insert into DATABASE_NAME.ingredient (ID, name) values (342, 'Cheese - Manchego, Spanish');
insert into DATABASE_NAME.ingredient (ID, name) values (343, 'Honey - Comb');
insert into DATABASE_NAME.ingredient (ID, name) values (344, 'Sprouts - Corn');
insert into DATABASE_NAME.ingredient (ID, name) values (345, 'Marsala - Sperone, Fine, D.o.c.');
insert into DATABASE_NAME.ingredient (ID, name) values (346, 'Schnappes Peppermint - Walker');
insert into DATABASE_NAME.ingredient (ID, name) values (347, 'Gatorade - Cool Blue Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (348, 'Rabbit - Saddles');
insert into DATABASE_NAME.ingredient (ID, name) values (349, 'Pasta - Lasagne, Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (350, 'Chocolate - Chips Compound');
insert into DATABASE_NAME.ingredient (ID, name) values (351, 'Berry Brulee');
insert into DATABASE_NAME.ingredient (ID, name) values (352, 'Chocolate - Pistoles, Lactee, Milk');
insert into DATABASE_NAME.ingredient (ID, name) values (353, 'Wine - Charddonnay Errazuriz');
insert into DATABASE_NAME.ingredient (ID, name) values (354, 'Pork Loin Bine - In Frenched');
insert into DATABASE_NAME.ingredient (ID, name) values (355, 'Water, Tap');
insert into DATABASE_NAME.ingredient (ID, name) values (356, 'Lemon Tarts');
insert into DATABASE_NAME.ingredient (ID, name) values (357, 'Pasta - Detalini, White, Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (358, 'Wine - Cava Aria Estate Brut');
insert into DATABASE_NAME.ingredient (ID, name) values (359, 'Butter Sweet');
insert into DATABASE_NAME.ingredient (ID, name) values (360, 'Cheese - Asiago');
insert into DATABASE_NAME.ingredient (ID, name) values (361, 'Nut - Pumpkin Seeds');
insert into DATABASE_NAME.ingredient (ID, name) values (362, 'Gloves - Goldtouch Disposable');
insert into DATABASE_NAME.ingredient (ID, name) values (363, 'Spice - Onion Powder Granulated');
insert into DATABASE_NAME.ingredient (ID, name) values (364, 'Crackers - Trio');
insert into DATABASE_NAME.ingredient (ID, name) values (365, 'Tomatoes - Diced, Canned');
insert into DATABASE_NAME.ingredient (ID, name) values (366, 'Doilies - 10, Paper');
insert into DATABASE_NAME.ingredient (ID, name) values (367, 'Fish - Soup Base, Bouillon');
insert into DATABASE_NAME.ingredient (ID, name) values (368, 'Water Chestnut - Canned');
insert into DATABASE_NAME.ingredient (ID, name) values (369, 'Chicken - White Meat, No Tender');
insert into DATABASE_NAME.ingredient (ID, name) values (370, 'Sauce - Cranberry');
insert into DATABASE_NAME.ingredient (ID, name) values (371, 'Peach - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (372, 'Veal - Chops, Split, Frenched');
insert into DATABASE_NAME.ingredient (ID, name) values (373, 'Ham - Procutinni');
insert into DATABASE_NAME.ingredient (ID, name) values (374, 'Veal - Nuckle');
insert into DATABASE_NAME.ingredient (ID, name) values (375, 'Bread Base - Gold Formel');
insert into DATABASE_NAME.ingredient (ID, name) values (376, 'Mix - Cappucino Cocktail');
insert into DATABASE_NAME.ingredient (ID, name) values (377, 'Pork - Bones');
insert into DATABASE_NAME.ingredient (ID, name) values (378, 'Swordfish Loin Portions');
insert into DATABASE_NAME.ingredient (ID, name) values (379, 'Rye Special Old');
insert into DATABASE_NAME.ingredient (ID, name) values (380, 'Sponge Cake Mix - Vanilla');
insert into DATABASE_NAME.ingredient (ID, name) values (381, 'Sausage - Meat');
insert into DATABASE_NAME.ingredient (ID, name) values (382, 'Cheese - Cheddar With Claret');
insert into DATABASE_NAME.ingredient (ID, name) values (383, 'Compound - Pear');
insert into DATABASE_NAME.ingredient (ID, name) values (384, 'Cookies - Englishbay Wht');
insert into DATABASE_NAME.ingredient (ID, name) values (385, 'Cheese Cloth');
insert into DATABASE_NAME.ingredient (ID, name) values (386, 'Soup - Campbells Broccoli');
insert into DATABASE_NAME.ingredient (ID, name) values (387, 'Soup - Campbells Mac N Cheese');
insert into DATABASE_NAME.ingredient (ID, name) values (388, 'Rice - Wild');
insert into DATABASE_NAME.ingredient (ID, name) values (389, 'Juice - Lime');
insert into DATABASE_NAME.ingredient (ID, name) values (390, 'Tea Peppermint');
insert into DATABASE_NAME.ingredient (ID, name) values (391, 'Tarts Assorted');
insert into DATABASE_NAME.ingredient (ID, name) values (392, 'Pork - Loin, Bone - In');
insert into DATABASE_NAME.ingredient (ID, name) values (393, 'Lidsoupcont Rp12dn');
insert into DATABASE_NAME.ingredient (ID, name) values (394, 'Bagelers - Cinn / Brown');
insert into DATABASE_NAME.ingredient (ID, name) values (395, 'Durian Fruit');
insert into DATABASE_NAME.ingredient (ID, name) values (396, 'Wiberg Super Cure');
insert into DATABASE_NAME.ingredient (ID, name) values (397, 'Juice - Lime');
insert into DATABASE_NAME.ingredient (ID, name) values (398, 'Lentils - Red, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (399, 'Beans - Kidney, Red Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (400, 'Flavouring - Rum');
insert into DATABASE_NAME.ingredient (ID, name) values (401, 'Wine - Alsace Riesling Reserve');
insert into DATABASE_NAME.ingredient (ID, name) values (402, 'Danishes - Mini Cheese');
insert into DATABASE_NAME.ingredient (ID, name) values (403, 'Wine - Tio Pepe Sherry Fino');
insert into DATABASE_NAME.ingredient (ID, name) values (404, 'Wine - Sogrape Mateus Rose');
insert into DATABASE_NAME.ingredient (ID, name) values (405, 'Myers Planters Punch');
insert into DATABASE_NAME.ingredient (ID, name) values (406, 'Bread - Roll, Italian');
insert into DATABASE_NAME.ingredient (ID, name) values (407, 'Wine - White, Chardonnay');
insert into DATABASE_NAME.ingredient (ID, name) values (408, 'Juice - Ocean Spray Kiwi');
insert into DATABASE_NAME.ingredient (ID, name) values (409, 'Kaffir Lime Leaves');
insert into DATABASE_NAME.ingredient (ID, name) values (410, 'Propel Sport Drink');
insert into DATABASE_NAME.ingredient (ID, name) values (411, 'Pasta - Angel Hair');
insert into DATABASE_NAME.ingredient (ID, name) values (412, 'Juice - Apple, 1.36l');
insert into DATABASE_NAME.ingredient (ID, name) values (413, 'Cleaner - Comet');
insert into DATABASE_NAME.ingredient (ID, name) values (414, 'Cookie Dough - Oatmeal Rasin');
insert into DATABASE_NAME.ingredient (ID, name) values (415, 'Browning Caramel Glace');
insert into DATABASE_NAME.ingredient (ID, name) values (416, 'Pate - Liver');
insert into DATABASE_NAME.ingredient (ID, name) values (417, 'Salmon - Atlantic, No Skin');
insert into DATABASE_NAME.ingredient (ID, name) values (418, 'Pasta - Shells, Medium, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (419, 'Pears - Fiorelle');
insert into DATABASE_NAME.ingredient (ID, name) values (420, 'Cheese - Stilton');
insert into DATABASE_NAME.ingredient (ID, name) values (421, 'Potatoes - Yukon Gold 5 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (422, 'Chocolate - Unsweetened');
insert into DATABASE_NAME.ingredient (ID, name) values (423, 'Snapple - Iced Tea Peach');
insert into DATABASE_NAME.ingredient (ID, name) values (424, 'Alize Sunset');
insert into DATABASE_NAME.ingredient (ID, name) values (425, 'Soup - Knorr, Country Bean');
insert into DATABASE_NAME.ingredient (ID, name) values (426, 'Longos - Lasagna Veg');
insert into DATABASE_NAME.ingredient (ID, name) values (427, 'Muffin Mix - Morning Glory');
insert into DATABASE_NAME.ingredient (ID, name) values (428, 'Apron');
insert into DATABASE_NAME.ingredient (ID, name) values (429, 'Chips - Doritos');
insert into DATABASE_NAME.ingredient (ID, name) values (430, 'Bonito Flakes - Toku Katsuo');
insert into DATABASE_NAME.ingredient (ID, name) values (431, 'Foam Tray S2');
insert into DATABASE_NAME.ingredient (ID, name) values (432, 'Horseradish - Prepared');
insert into DATABASE_NAME.ingredient (ID, name) values (433, 'Persimmons');
insert into DATABASE_NAME.ingredient (ID, name) values (434, 'Steampan - Lid For Half Size');
insert into DATABASE_NAME.ingredient (ID, name) values (435, 'Versatainer Nc - 9388');
insert into DATABASE_NAME.ingredient (ID, name) values (436, 'Lettuce - Romaine');
insert into DATABASE_NAME.ingredient (ID, name) values (437, 'Wine - White Cab Sauv.on');
insert into DATABASE_NAME.ingredient (ID, name) values (438, 'Juice Peach Nectar');
insert into DATABASE_NAME.ingredient (ID, name) values (439, 'Carrots - Mini Red Organic');
insert into DATABASE_NAME.ingredient (ID, name) values (440, 'Wine - Red, Antinori Santa');
insert into DATABASE_NAME.ingredient (ID, name) values (441, 'Tart Shells - Savory, 4');
insert into DATABASE_NAME.ingredient (ID, name) values (442, 'Bread Base - Gold Formel');
insert into DATABASE_NAME.ingredient (ID, name) values (443, 'Wine - Marlbourough Sauv Blanc');
insert into DATABASE_NAME.ingredient (ID, name) values (444, 'Goat - Whole Cut');
insert into DATABASE_NAME.ingredient (ID, name) values (445, 'Bread - White, Unsliced');
insert into DATABASE_NAME.ingredient (ID, name) values (446, 'Fish - Scallops, Cold Smoked');
insert into DATABASE_NAME.ingredient (ID, name) values (447, 'Salt - Rock, Course');
insert into DATABASE_NAME.ingredient (ID, name) values (448, 'Pork - Backs - Boneless');
insert into DATABASE_NAME.ingredient (ID, name) values (449, 'Goldschalger');
insert into DATABASE_NAME.ingredient (ID, name) values (450, 'Mushroom - Morel Frozen');
insert into DATABASE_NAME.ingredient (ID, name) values (451, 'Yogurt - Blueberry, 175 Gr');
insert into DATABASE_NAME.ingredient (ID, name) values (452, 'Wine - Manischewitz Concord');
insert into DATABASE_NAME.ingredient (ID, name) values (453, 'Chicken - Bones');
insert into DATABASE_NAME.ingredient (ID, name) values (454, 'Broom And Brush Rack Black');
insert into DATABASE_NAME.ingredient (ID, name) values (455, 'Jam - Raspberry');
insert into DATABASE_NAME.ingredient (ID, name) values (456, 'Pork - Tenderloin, Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (457, 'Soup - Campbells, Lentil');
insert into DATABASE_NAME.ingredient (ID, name) values (458, 'Sauce - Rosee');
insert into DATABASE_NAME.ingredient (ID, name) values (459, 'Mop Head - Cotton, 24 Oz');
insert into DATABASE_NAME.ingredient (ID, name) values (460, 'Otomegusa Dashi Konbu');
insert into DATABASE_NAME.ingredient (ID, name) values (461, 'Chocolate - Milk Coating');
insert into DATABASE_NAME.ingredient (ID, name) values (462, 'Pea - Snow');
insert into DATABASE_NAME.ingredient (ID, name) values (463, 'Five Alive Citrus');
insert into DATABASE_NAME.ingredient (ID, name) values (464, 'Wine - Shiraz South Eastern');
insert into DATABASE_NAME.ingredient (ID, name) values (465, 'Bouillion - Fish');
insert into DATABASE_NAME.ingredient (ID, name) values (466, 'Oil - Sesame');
insert into DATABASE_NAME.ingredient (ID, name) values (467, 'Roe - Lump Fish, Red');
insert into DATABASE_NAME.ingredient (ID, name) values (468, 'Club Soda - Schweppes, 355 Ml');
insert into DATABASE_NAME.ingredient (ID, name) values (469, 'Quail - Whole, Bone - In');
insert into DATABASE_NAME.ingredient (ID, name) values (470, 'Bar - Granola Trail Mix Fruit Nut');
insert into DATABASE_NAME.ingredient (ID, name) values (471, 'Juice - Orange, 341 Ml');
insert into DATABASE_NAME.ingredient (ID, name) values (472, 'Mini - Vol Au Vents');
insert into DATABASE_NAME.ingredient (ID, name) values (473, 'Cheese - Swiss Sliced');
insert into DATABASE_NAME.ingredient (ID, name) values (474, 'Juice - Orangina');
insert into DATABASE_NAME.ingredient (ID, name) values (475, 'Wine - Red, Wolf Blass, Yellow');
insert into DATABASE_NAME.ingredient (ID, name) values (476, 'Sage - Ground');
insert into DATABASE_NAME.ingredient (ID, name) values (477, 'Ice Cream - Chocolate');
insert into DATABASE_NAME.ingredient (ID, name) values (478, 'Towel Multifold');
insert into DATABASE_NAME.ingredient (ID, name) values (479, 'Kumquat');
insert into DATABASE_NAME.ingredient (ID, name) values (480, 'Tea - Herbal - 6 Asst');
insert into DATABASE_NAME.ingredient (ID, name) values (481, 'Tofu - Soft');
insert into DATABASE_NAME.ingredient (ID, name) values (482, 'The Pop Shoppe - Grape');
insert into DATABASE_NAME.ingredient (ID, name) values (483, 'Beer - Mill St Organic');
insert into DATABASE_NAME.ingredient (ID, name) values (484, 'Veal - Inside, Choice');
insert into DATABASE_NAME.ingredient (ID, name) values (485, 'Sage - Fresh');
insert into DATABASE_NAME.ingredient (ID, name) values (486, 'Split Peas - Yellow, Dry');
insert into DATABASE_NAME.ingredient (ID, name) values (487, 'Fish - Atlantic Salmon, Cold');
insert into DATABASE_NAME.ingredient (ID, name) values (488, 'Scallops 60/80 Iqf');
insert into DATABASE_NAME.ingredient (ID, name) values (489, 'Soup - French Onion');
insert into DATABASE_NAME.ingredient (ID, name) values (490, 'Cookies - Oreo, 4 Pack');
insert into DATABASE_NAME.ingredient (ID, name) values (491, 'Bar Mix - Lemon');
insert into DATABASE_NAME.ingredient (ID, name) values (492, 'Bread Base - Goodhearth');
insert into DATABASE_NAME.ingredient (ID, name) values (493, 'Longos - Assorted Sandwich');
insert into DATABASE_NAME.ingredient (ID, name) values (494, 'Wine - Tribal Sauvignon');
insert into DATABASE_NAME.ingredient (ID, name) values (495, 'Bay Leaf');
insert into DATABASE_NAME.ingredient (ID, name) values (496, 'Pepper - White, Ground');
insert into DATABASE_NAME.ingredient (ID, name) values (497, 'Lambcasing');
insert into DATABASE_NAME.ingredient (ID, name) values (498, 'Pork - Caul Fat');
insert into DATABASE_NAME.ingredient (ID, name) values (499, 'Tart - Butter Plain Squares');
insert into DATABASE_NAME.ingredient (ID, name) values (500, 'Bread Base - Toscano');
